### ISSUE TITLE
a feature that restores the phone's volume mode when disconnecting

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/bluemusic#49]
> Hi, I enjoy your app but wondering if there is anyway to add a feature that restores the phone's volume mode when disconnecting? I normally have my phone on vibrate for notifications and ringing. Your app changes to play sounds when connected, which I like since the phone is on a mount when in the car so vibrating is pointless. However when I leave the car and have the phone in my pocket, it does not restore the vibrate mode. 

https://mail.google.com/mail/ca/u/0/#label/%40darken.eu%2Fsupport/FMfcgxvzMBnzrNsNRXZwbfKBHjsqHRXs

**Comment by Offerel** [comment]
This would be really awesome...

**Comment by d4rken** [comment]
Good news, this is already implemented. You can add the phone itself as managed device which will "connect" once all Bluetooth devices disconnect.
